apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt
  labels:
    app: nuxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
        - name: nuxt
          image: cr.selcloud.ru/viva/viva_front:latest
          ports:
            - containerPort: 3000
              name: nuxt-port
