# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
spec:
  selector:
    app: nuxt
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
