apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: viva-grafana
  name: viva-grafana
spec:
  selector:
    matchLabels:
      app: viva-grafana
  template:
    metadata:
      labels:
        app: viva-grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: viva-grafana
          image: dockerhub.timeweb.cloud/grafana/grafana
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: viva-grafana-persistent
      volumes:
        - name: viva-grafana-persistent
          persistentVolumeClaim:
            claimName: viva-grafana-persistentc
