# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: viva-prometheus-service
spec:
  selector:
    app: viva-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

